version: '3'

services:
  ipsc-practice-app-php-fpm:
    image: php:8-fpm
    container_name: ipsc-practice-app-php-fpm
    volumes:
      - ./config/php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./public:${WEBROOT}
    networks:
      - app-network
    restart: unless-stopped

  ipsc-practice-app-nginx:
    image: nginx:latest
    container_name: ipsc-practice-app-nginx
    ports:
      - ${PORT}:${PORT}
    extra_hosts:
      - ${DOMAIN}:${IP}
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ./public:${WEBROOT}
    environment:
      PORT: ${PORT}
      DOMAIN: ${DOMAIN}
    networks:
      - app-network
    restart: unless-stopped

volumes:
  config:
  public:

networks:
  app-network:
    external: true
