version: '3'

services:
  ipsc-practice-app-php-fpm:
    image: php:8-fpm
    container_name: ipsc-practice-app-php-fpm
    volumes:
      - ./config/php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./public:${WEBROOT}
    networks:
      - app-network

  ipsc-practice-app-nginx:
    image: nginx:latest
    container_name: ipsc-practice-app-nginx
    ports:
      - ${PORT}:${PORT}
    extra_hosts:
      - ${DOMAIN}:${IP}
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ./config/nginx/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf
      - ./certbot-etc:/etc/letsencrypt
      - ./public:${WEBROOT}
    environment:
      PORT: ${PORT}
      DOMAIN: ${DOMAIN}
    networks:
      - app-network

  ipsc-practice-app-certbot:
    depends_on:
      - ipsc-practice-app-nginx
    image: certbot/certbot
    container_name: ipsc-practice-app-certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./public:${WEBROOT}
    networks:
      - app-network

volumes:
  certbot-etc:
  config:
  public:

networks:
  app-network:
    external: true
    #driver: bridge