version: '3'

services:
  php-fpm:
    image: php:8-fpm
    container_name: php-fpm
    volumes:
      - ./config/php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./public:${WEBROOT}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - ${DOMAIN}:${IP}
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ./config/nginx/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf
      - ./certbot-etc:/etc/letsencrypt
      - ./public:${WEBROOT}
    networks:
      - app-network

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./public:${WEBROOT}
    networks:
      - app-network

volumes:
  certbot-etc:
  config:
  public:

networks:
  app-network:
    driver: bridge