version: '3'

services:
  php-fpm:
    image: php:8-fpm
    container_name: php-fpm
    volumes:
      - ./config/php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./public:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - ${IP}:${PORT_HTTP}:80
      - ${IP}:${PORT_HTTPS}:443
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf
      - ./certbot-etc:/etc/letsencrypt
      - ./public:/var/www/html
    links:
      - php-fpm
    networks:
      - app-network

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./public:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email ${SSL_ENV} -d ${DOMAIN} -d www.${DOMAIN}
    networks:
      - app-network

volumes:
  certbot-etc:
  config:
  public:

networks:
  app-network:
    driver: bridge