version: '3'

services:
  php-fpm:
    image: php:8-fpm
    container_name: php-fpm
    volumes:
      - ./config/php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./public:${WEBROOT}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - ${IP}:${PORT_HTTP}:80
    extra_hosts:
      - ${DOMAIN}:${IP}
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ./public:${WEBROOT}
    networks:
      - app-network

volumes:
  config:
  public:

networks:
  app-network:
    driver: bridge